[package]
edition = "2018"
name = "raygun"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "raygun"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
